#!/usr/bin/env python3
"""Append sections 3-7 to mega-stress-test.md"""

import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "test-fixtures", "mega-stress-test.md")
lines = []
def w(s=""): lines.append(s)

# ═══════════════════════════════════════════════════════════════════
# SECTION 3: SUPER LONG CODE BLOCK (200+ lines)
# ═══════════════════════════════════════════════════════════════════
w("---")
w()
w("## Section 3: Super Long Code Block (200+ lines)")
w()
w("This tests rendering performance with a very long code block:")
w()
w("```python")
w('"""')
w("Complete HTTP API framework with routing, middleware, and request handling.")
w("This is a 200+ line code block to stress-test CodeMirror rendering.")
w('"""')
w("import json")
w("import re")
w("import socket")
w("import threading")
w("from dataclasses import dataclass, field")
w("from enum import Enum")
w("from typing import Any, Callable, Optional")
w("from urllib.parse import parse_qs, urlparse")
w("")
w("")
w("class HttpMethod(Enum):")
w('    GET = "GET"')
w('    POST = "POST"')
w('    PUT = "PUT"')
w('    DELETE = "DELETE"')
w('    PATCH = "PATCH"')
w('    OPTIONS = "OPTIONS"')
w("")
w("")
w("@dataclass")
w("class Request:")
w('    method: str = "GET"')
w('    path: str = "/"')
w("    headers: dict = field(default_factory=dict)")
w("    query_params: dict = field(default_factory=dict)")
w("    body: bytes = b''")
w("    path_params: dict = field(default_factory=dict)")
w("")
w("    @property")
w("    def json(self) -> Any:")
w("        try:")
w("            return json.loads(self.body.decode('utf-8'))")
w("        except (json.JSONDecodeError, UnicodeDecodeError):")
w("            return None")
w("")
w("    @property")
w("    def content_type(self) -> str:")
w('        return self.headers.get("content-type", "")')
w("")
w("")
w("@dataclass")
w("class Response:")
w("    status_code: int = 200")
w('    body: str = ""')
w("    headers: dict = field(default_factory=dict)")
w("")
w("    def to_bytes(self) -> bytes:")
w("        status_messages = {")
w('            200: "OK", 201: "Created", 204: "No Content",')
w('            400: "Bad Request", 401: "Unauthorized", 403: "Forbidden",')
w('            404: "Not Found", 405: "Method Not Allowed",')
w('            500: "Internal Server Error",')
w("        }")
w('        status_msg = status_messages.get(self.status_code, "Unknown")')
w('        headers = self.headers.copy()')
w('        headers.setdefault("Content-Type", "application/json")')
w('        headers["Content-Length"] = str(len(self.body.encode("utf-8")))')
w('        header_lines = "\\r\\n".join(f"{k}: {v}" for k, v in headers.items())')
w(f'        return f"HTTP/1.1 {{self.status_code}} {{status_msg}}\\r\\n{{header_lines}}\\r\\n\\r\\n{{self.body}}".encode("utf-8")')
w("")
w("")
w("def json_response(data: Any, status: int = 200) -> Response:")
w("    return Response(")
w("        status_code=status,")
w("        body=json.dumps(data, indent=2),")
w('        headers={"Content-Type": "application/json"},')
w("    )")
w("")
w("")
w("class Router:")
w("    def __init__(self):")
w("        self.routes: list[tuple[str, str, Callable]] = []")
w("        self.middleware: list[Callable] = []")
w("")
w("    def route(self, method: str, path: str):")
w("        def decorator(handler: Callable):")
w("            pattern = re.sub(r':([\\w]+)', r'(?P<\\1>[\\w-]+)', path)")
w("            self.routes.append((method.upper(), pattern, handler))")
w("            return handler")
w("        return decorator")
w("")
w("    def get(self, path: str):")
w('        return self.route("GET", path)')
w("")
w("    def post(self, path: str):")
w('        return self.route("POST", path)')
w("")
w("    def put(self, path: str):")
w('        return self.route("PUT", path)')
w("")
w("    def delete(self, path: str):")
w('        return self.route("DELETE", path)')
w("")
w("    def use(self, middleware: Callable):")
w("        self.middleware.append(middleware)")
w("")
w("    def resolve(self, method: str, path: str) -> Optional[tuple[Callable, dict]]:")
w("        for route_method, pattern, handler in self.routes:")
w("            if route_method != method.upper():")
w("                continue")
w('            match = re.fullmatch(pattern, path)')
w("            if match:")
w("                return handler, match.groupdict()")
w("        return None")
w("")
w("")
w("class HttpServer:")
w("    def __init__(self, host: str = '0.0.0.0', port: int = 8080):")
w("        self.host = host")
w("        self.port = port")
w("        self.router = Router()")
w("        self._running = False")
w("")
w("    def parse_request(self, raw: bytes) -> Request:")
w('        text = raw.decode("utf-8", errors="replace")')
w('        lines = text.split("\\r\\n")')
w('        method, path_query, _ = lines[0].split(" ", 2)')
w("        parsed = urlparse(path_query)")
w("        headers = {}")
w("        body_start = 0")
w("        for i, line in enumerate(lines[1:], 1):")
w("            if not line:")
w("                body_start = i + 1")
w("                break")
w('            key, _, value = line.partition(": ")')
w("            headers[key.lower()] = value")
w('        body = "\\r\\n".join(lines[body_start:]).encode("utf-8") if body_start else b""')
w("        return Request(")
w("            method=method,")
w("            path=parsed.path,")
w("            headers=headers,")
w("            query_params=parse_qs(parsed.query),")
w("            body=body,")
w("        )")
w("")
w("    def handle_client(self, conn: socket.socket, addr: tuple):")
w("        try:")
w("            raw = conn.recv(65536)")
w("            if not raw:")
w("                return")
w("            request = self.parse_request(raw)")
w("            # Apply middleware")
w("            for mw in self.router.middleware:")
w("                result = mw(request)")
w("                if isinstance(result, Response):")
w("                    conn.sendall(result.to_bytes())")
w("                    return")
w("            # Route matching")
w("            match = self.router.resolve(request.method, request.path)")
w("            if match:")
w("                handler, path_params = match")
w("                request.path_params = path_params")
w("                response = handler(request)")
w("            else:")
w('                response = json_response({"error": "Not Found"}, 404)')
w("            conn.sendall(response.to_bytes())")
w("        except Exception as e:")
w('            error_resp = json_response({"error": str(e)}, 500)')
w("            conn.sendall(error_resp.to_bytes())")
w("        finally:")
w("            conn.close()")
w("")
w("    def start(self):")
w("        self._running = True")
w("        server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)")
w("        server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)")
w("        server.bind((self.host, self.port))")
w("        server.listen(128)")
w(f'        print(f"Listening on {{self.host}}:{{self.port}}")')
w("        while self._running:")
w("            conn, addr = server.accept()")
w("            thread = threading.Thread(target=self.handle_client, args=(conn, addr))")
w("            thread.daemon = True")
w("            thread.start()")
w("")
w("")
w("# Example usage")
w('if __name__ == "__main__":')
w("    app = HttpServer(port=3000)")
w("    router = app.router")
w("")
w("    # In-memory store")
w("    users = {}")
w("    next_id = 1")
w("")
w("    # Logging middleware")
w("    def log_request(req: Request):")
w(f'        print(f"{{req.method}} {{req.path}}")')
w("        return None  # Continue processing")
w("")
w("    router.use(log_request)")
w("")
w('    @router.get("/api/users")')
w("    def list_users(req: Request) -> Response:")
w("        return json_response(list(users.values()))")
w("")
w('    @router.get("/api/users/:id")')
w("    def get_user(req: Request) -> Response:")
w('        user_id = int(req.path_params["id"])')
w("        if user_id in users:")
w("            return json_response(users[user_id])")
w('        return json_response({"error": "User not found"}, 404)')
w("")
w('    @router.post("/api/users")')
w("    def create_user(req: Request) -> Response:")
w("        global next_id")
w("        data = req.json")
w("        if not data or 'name' not in data:")
w('            return json_response({"error": "name required"}, 400)')
w('        user = {"id": next_id, "name": data["name"], "email": data.get("email", "")}')
w("        users[next_id] = user")
w("        next_id += 1")
w("        return json_response(user, 201)")
w("")
w('    @router.delete("/api/users/:id")')
w("    def delete_user(req: Request) -> Response:")
w('        user_id = int(req.path_params["id"])')
w("        if user_id in users:")
w("            del users[user_id]")
w('            return Response(status_code=204, body="")')
w('        return json_response({"error": "User not found"}, 404)')
w("")
w("    app.start()")
w("```")
w()

# ═══════════════════════════════════════════════════════════════════
# SECTION 4: COMPLEX MERMAID DIAGRAMS
# ═══════════════════════════════════════════════════════════════════
w("---")
w()
w("## Section 4: Complex Mermaid Diagrams")
w()

w("### 4A: Complex Flowchart (20+ nodes, subgraphs)")
w()
w("```mermaid")
w("flowchart TD")
w("    Start([Start]) --> InputValidation{Valid Input?}")
w("    InputValidation -->|Yes| Auth{Authenticated?}")
w("    InputValidation -->|No| ErrorResponse[400 Bad Request]")
w("    Auth -->|Yes| RateLimit{Rate Limited?}")
w("    Auth -->|No| AuthError[401 Unauthorized]")
w("    RateLimit -->|Yes| RateLimitError[429 Too Many Requests]")
w("    RateLimit -->|No| RouteMatch{Route Found?}")
w("    RouteMatch -->|No| NotFound[404 Not Found]")
w("    RouteMatch -->|Yes| Middleware")
w("")
w("    subgraph Middleware[Middleware Pipeline]")
w("        direction TB")
w("        MW1[CORS Check] --> MW2[Body Parser]")
w("        MW2 --> MW3[Request Logger]")
w("        MW3 --> MW4[Compression]")
w("    end")
w("")
w("    Middleware --> Handler")
w("")
w("    subgraph Handler[Request Handler]")
w("        direction TB")
w("        H1{GET or POST?}")
w("        H1 -->|GET| ReadDB[(Read Database)]")
w("        H1 -->|POST| ValidateBody{Body Valid?}")
w("        ValidateBody -->|Yes| WriteDB[(Write Database)]")
w("        ValidateBody -->|No| ValidationError[422 Error]")
w("        ReadDB --> Transform[Transform Data]")
w("        WriteDB --> Transform")
w("    end")
w("")
w("    Handler --> Cache{Cacheable?}")
w("    Cache -->|Yes| SetCache[Set Cache Header]")
w("    Cache -->|No| SuccessResponse")
w("    SetCache --> SuccessResponse[200 Success]")
w("")
w("    ErrorResponse --> End([End])")
w("    AuthError --> End")
w("    RateLimitError --> End")
w("    NotFound --> End")
w("    SuccessResponse --> End")
w("")
w("    style Start fill:#4CAF50,color:#fff")
w("    style End fill:#f44336,color:#fff")
w("    style ErrorResponse fill:#ff9800,color:#fff")
w("    style SuccessResponse fill:#2196F3,color:#fff")
w("```")
w()

w("### 4B: Complex Sequence Diagram (6+ participants)")
w()
w("```mermaid")
w("sequenceDiagram")
w("    participant C as Client")
w("    participant LB as Load Balancer")
w("    participant API as API Server")
w("    participant Auth as Auth Service")
w("    participant Cache as Redis Cache")
w("    participant DB as PostgreSQL")
w("    participant Queue as Message Queue")
w("    participant Worker as Background Worker")
w("")
w("    C->>+LB: POST /api/orders")
w("    LB->>+API: Forward request")
w("    API->>+Auth: Validate JWT token")
w("    Auth-->>-API: Token valid (user_id: 42)")
w("")
w("    API->>+Cache: Check rate limit (user:42)")
w("    Cache-->>-API: 45/100 requests (OK)")
w("")
w("    alt Valid Order")
w("        API->>+DB: BEGIN TRANSACTION")
w("        API->>DB: INSERT INTO orders")
w("        API->>DB: UPDATE inventory SET quantity = quantity - 1")
w("        DB-->>-API: COMMIT OK")
w("")
w("        API->>+Queue: Publish order.created event")
w("        Queue-->>-API: ACK")
w("")
w("        API-->>C: 201 Created {order_id: 789}")
w("")
w("        Note over Queue,Worker: Async processing")
w("        Queue->>+Worker: Consume order.created")
w("        Worker->>DB: Update order status")
w("        Worker->>Worker: Send confirmation email")
w("        Worker-->>-Queue: ACK processed")
w("    else Invalid Order")
w("        API-->>C: 400 Bad Request")
w("    end")
w("")
w("    deactivate API")
w("    deactivate LB")
w("```")
w()

w("### 4C: Class Diagram (5+ classes)")
w()
w("```mermaid")
w("classDiagram")
w("    class Document {")
w("        +String id")
w("        +String title")
w("        +String content")
w("        +DateTime createdAt")
w("        +DateTime updatedAt")
w("        +save() Promise~Document~")
w("        +delete() Promise~void~")
w("        +toMarkdown() String")
w("    }")
w("")
w("    class Editor {")
w("        -WKWebView webView")
w("        -WebBridge bridge")
w("        -Boolean isDirty")
w("        +loadDocument(doc: Document) void")
w("        +getContent() String")
w("        +setTheme(theme: Theme) void")
w("        +execCommand(cmd: String) Boolean")
w("    }")
w("")
w("    class WebBridge {")
w("        -WKWebView webView")
w("        +callJS(method: String, args: Dict) Promise~Any~")
w("        +getMarkdown() Promise~String~")
w("        +setMarkdown(md: String) Promise~void~")
w("    }")
w("")
w("    class NativeBridge {")
w("        <<interface>>")
w("        +onContentChanged(markdown: String) void")
w("        +onEditorReady() void")
w("        +onError(message: String) void")
w("        +onScrollChanged(position: Number) void")
w("    }")
w("")
w("    class EditorPool {")
w("        -Map~String, Editor~ active")
w("        -Array~Editor~ available")
w("        -Int maxLive")
w("        +acquire() Editor")
w("        +release(editor: Editor) void")
w("        +virtualize(editor: Editor) void")
w("        +rehydrate(editor: Editor) void")
w("    }")
w("")
w("    class Theme {")
w("        <<enumeration>>")
w("        LIGHT")
w("        DARK")
w("        AUTO")
w("    }")
w("")
w("    Document --> Editor : opened in")
w("    Editor --> WebBridge : uses")
w("    Editor ..|> NativeBridge : implements")
w("    EditorPool --> Editor : manages")
w("    Editor --> Theme : applies")
w("```")
w()

w("### 4D: State Diagram (10+ states)")
w()
w("```mermaid")
w("stateDiagram-v2")
w("    [*] --> Idle")
w("")
w("    state Idle {")
w("        [*] --> WaitingForFile")
w("        WaitingForFile --> FileSelected: User opens file")
w("    }")
w("")
w("    Idle --> Loading: File opened")
w("")
w("    state Loading {")
w("        [*] --> ReadingDisk")
w("        ReadingDisk --> ParsingMarkdown: File read")
w("        ParsingMarkdown --> InitEditor: Parsed")
w("        InitEditor --> SettingContent: Editor ready")
w("    }")
w("")
w("    Loading --> Editing: Content loaded")
w("    Loading --> Error: Read/parse failure")
w("")
w("    state Editing {")
w("        [*] --> Clean")
w("        Clean --> Dirty: Content changed")
w("        Dirty --> Saving: Auto-save triggered")
w("        Saving --> Clean: Save success")
w("        Saving --> Dirty: Save failed")
w("    }")
w("")
w("    Editing --> Reloading: External file change")
w("    Editing --> Virtualized: Tab backgrounded")
w("    Editing --> Closing: Window closed")
w("")
w("    Reloading --> Editing: Content updated")
w("    Reloading --> Error: Reload failed")
w("")
w("    state Virtualized {")
w("        [*] --> Stored")
w("        Stored --> Rehydrating: Tab foregrounded")
w("        Rehydrating --> Restored: WebView ready")
w("    }")
w("")
w("    Virtualized --> Editing: Tab restored")
w("")
w("    Closing --> [*]")
w("    Error --> Idle: User dismisses")
w("```")
w()

w("### 4E: Entity Relationship Diagram")
w()
w("```mermaid")
w("erDiagram")
w("    USER ||--o{ DOCUMENT : creates")
w("    USER ||--o{ SESSION : has")
w("    DOCUMENT ||--|{ REVISION : contains")
w("    DOCUMENT ||--o{ TAG : tagged_with")
w("    DOCUMENT }o--|| WORKSPACE : belongs_to")
w("    WORKSPACE ||--o{ USER : members")
w("")
w("    USER {")
w("        uuid id PK")
w("        string name")
w("        string email UK")
w("        timestamp created_at")
w("        string avatar_url")
w("    }")
w("    DOCUMENT {")
w("        uuid id PK")
w("        uuid user_id FK")
w("        uuid workspace_id FK")
w("        string title")
w("        text content")
w("        enum status")
w("        timestamp updated_at")
w("    }")
w("    REVISION {")
w("        uuid id PK")
w("        uuid document_id FK")
w("        int version")
w("        text diff")
w("        timestamp created_at")
w("    }")
w("    TAG {")
w("        uuid id PK")
w("        string name UK")
w("        string color")
w("    }")
w("    WORKSPACE {")
w("        uuid id PK")
w("        string name")
w("        string slug UK")
w("        enum plan")
w("    }")
w("    SESSION {")
w("        uuid id PK")
w("        uuid user_id FK")
w("        string token")
w("        timestamp expires_at")
w("    }")
w("```")
w()

w("### 4F: Gantt Chart")
w()
w("```mermaid")
w("gantt")
w("    title Kern Editor Development Timeline")
w("    dateFormat YYYY-MM-DD")
w("")
w("    section Phase 1 - Core")
w("    CoreEditor HTML          :done, p1, 2025-01-01, 7d")
w("    Minimal Swift Shell      :done, p2, after p1, 5d")
w("    NSDocument Integration   :done, p3, after p2, 7d")
w("")
w("    section Phase 2 - Features")
w("    File Watching            :done, p4, after p3, 5d")
w("    Tab Virtualization       :done, p5, after p4, 7d")
w("    Themes + Menus           :done, p6, after p5, 5d")
w("")
w("    section Phase 3 - Polish")
w("    Bug Fixes                :active, p7, after p6, 10d")
w("    Performance Optimization :p8, after p7, 7d")
w("    Beta Testing             :p9, after p7, 14d")
w("    v1.0 Release             :milestone, after p9, 0d")
w("```")
w()

w("### 4G: Pie Chart")
w()
w("```mermaid")
w("pie title Kern Codebase Composition")
w('    "Swift" : 45')
w('    "TypeScript" : 25')
w('    "CSS" : 12')
w('    "HTML" : 5')
w('    "Shell Scripts" : 8')
w('    "Configuration" : 5')
w("```")
w()

w("### 4H: Git Graph")
w()
w("```mermaid")
w("gitGraph")
w("    commit id: \"init\"")
w('    commit id: "phase-1"')
w('    branch feature/document')
w('    commit id: "nsdocument"')
w('    commit id: "file-io"')
w('    checkout main')
w('    commit id: "phase-2"')
w('    merge feature/document')
w('    branch feature/tabs')
w('    commit id: "pool"')
w('    commit id: "virtualize"')
w('    checkout main')
w('    branch hotfix/blank-tabs')
w('    commit id: "fix-rehydrate"')
w('    checkout main')
w('    merge hotfix/blank-tabs')
w('    merge feature/tabs')
w('    commit id: "phase-6"')
w('    branch feature/mermaid')
w('    commit id: "render-preview"')
w('    checkout main')
w('    merge feature/mermaid')
w('    commit id: "v1.0"')
w("```")
w()

w("### 4I: Mindmap")
w()
w("```mermaid")
w("mindmap")
w("  root((Kern Editor))")
w("    Swift Layer")
w("      AppDelegate")
w("        Menu Bar")
w("        Theme Observer")
w("      NSDocument")
w("        File I/O")
w("        Autosave")
w("        File Watching")
w("      WKWebView")
w("        Pool of 5")
w("        Virtualization")
w("        Tab Support")
w("    Web Layer")
w("      Milkdown Crepe")
w("        ProseMirror")
w("        CodeMirror")
w("        KaTeX")
w("      Mermaid")
w("        Lazy Loading")
w("        SVG Rendering")
w("      Bridge")
w("        getMarkdown")
w("        setMarkdown")
w("        execCommand")
w("    Design")
w("      Notion-like UI")
w("      Dark Mode")
w("      SF Pro Fonts")
w("      720px Max Width")
w("```")
w()

w("### 4J: Timeline")
w()
w("```mermaid")
w("timeline")
w("    title Kern Development Timeline")
w("    2025-01 : Project Started")
w("             : Architecture Design")
w("    2025-02 : CoreEditor HTML")
w("             : Swift Shell")
w("             : NSDocument")
w("    2025-03 : File Watching")
w("             : Tab Virtualization")
w("    2025-04 : Themes and Polish")
w("             : Bug Fixes")
w("             : Beta Testing")
w("```")
w()

w("### 4K: Journey Diagram")
w()
w("```mermaid")
w("journey")
w("    title User Opens a Markdown File in Kern")
w("    section Discovery")
w("      Cmd-click file in terminal: 5: User")
w("      Kern launches: 4: System")
w("    section Loading")
w("      File read from disk: 5: Kern")
w("      Editor initializes: 4: Kern")
w("      WYSIWYG renders: 5: Kern")
w("    section Editing")
w("      User types content: 5: User")
w("      Auto-save triggers: 5: Kern")
w("      External change detected: 3: Kern")
w("      Content reloads: 4: Kern")
w("    section Multi-tab")
w("      Open more files: 4: User")
w("      Background tabs virtualized: 5: Kern")
w("      Switch tabs: 4: User")
w("      Tab rehydrates: 4: Kern")
w("```")
w()

w("### 4L: Sankey Diagram (experimental)")
w()
w("```mermaid")
w("sankey-beta")
w("")
w("Swift Code,App Shell,30")
w("Swift Code,Document,25")
w("Swift Code,Bridge,15")
w("Swift Code,Pool,10")
w("TypeScript,Editor,40")
w("TypeScript,Bridge,15")
w("TypeScript,Mermaid,10")
w("CSS,Theme,20")
w("CSS,Layout,15")
w("App Shell,Kern.app,30")
w("Document,Kern.app,25")
w("Bridge,Kern.app,30")
w("Pool,Kern.app,10")
w("Editor,index.html,40")
w("Theme,index.html,20")
w("Layout,index.html,15")
w("Mermaid,index.html,10")
w("```")
w()

# ═══════════════════════════════════════════════════════════════════
# SECTION 5: MATH/LATEX
# ═══════════════════════════════════════════════════════════════════
w("---")
w()
w("## Section 5: Math / LaTeX")
w()
w("### Inline Math")
w()
w("Simple: $E = mc^2$, $a^2 + b^2 = c^2$, $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$")
w()
w("Medium: $\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}$, $\\prod_{k=1}^{n} k = n!$, $\\int_0^1 x^2 dx = \\frac{1}{3}$")
w()
w("Complex: $\\oint_C \\mathbf{F} \\cdot d\\mathbf{r} = \\iint_S (\\nabla \\times \\mathbf{F}) \\cdot d\\mathbf{S}$")
w()
w("Greek: $\\alpha, \\beta, \\gamma, \\delta, \\epsilon, \\zeta, \\eta, \\theta, \\iota, \\kappa, \\lambda, \\mu, \\nu, \\xi, \\pi, \\rho, \\sigma, \\tau, \\upsilon, \\phi, \\chi, \\psi, \\omega$")
w()

w("### Block Math — Matrices")
w()
w("$$")
w("A = \\begin{pmatrix} a_{11} & a_{12} & a_{13} \\\\ a_{21} & a_{22} & a_{23} \\\\ a_{31} & a_{32} & a_{33} \\end{pmatrix}")
w("$$")
w()

w("### Block Math — Integral")
w()
w("$$")
w("\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}")
w("$$")
w()

w("### Block Math — Summation")
w()
w("$$")
w("\\sum_{n=0}^{\\infty} \\frac{x^n}{n!} = e^x")
w("$$")
w()

w("### Block Math — Piecewise Function")
w()
w("$$")
w("f(x) = \\begin{cases} x^2 & \\text{if } x \\geq 0 \\\\ -x^2 & \\text{if } x < 0 \\\\ \\text{undefined} & \\text{if } x = \\infty \\end{cases}")
w("$$")
w()

w("### Block Math — Aligned Equations")
w()
w("$$")
w("\\begin{aligned}")
w("\\nabla \\cdot \\mathbf{E} &= \\frac{\\rho}{\\epsilon_0} \\\\")
w("\\nabla \\cdot \\mathbf{B} &= 0 \\\\")
w("\\nabla \\times \\mathbf{E} &= -\\frac{\\partial \\mathbf{B}}{\\partial t} \\\\")
w("\\nabla \\times \\mathbf{B} &= \\mu_0 \\mathbf{J} + \\mu_0 \\epsilon_0 \\frac{\\partial \\mathbf{E}}{\\partial t}")
w("\\end{aligned}")
w("$$")
w()

w("### Block Math — Nested Fractions")
w()
w("$$")
w("\\cfrac{1}{1 + \\cfrac{1}{1 + \\cfrac{1}{1 + \\cfrac{1}{1 + \\cfrac{1}{x}}}}}")
w("$$")
w()

w("### Block Math — Very Long Equation")
w()
w("$$")
w("\\frac{d}{dx}\\left[\\int_{a(x)}^{b(x)} f(x, t) \\, dt\\right] = f(x, b(x)) \\cdot b'(x) - f(x, a(x)) \\cdot a'(x) + \\int_{a(x)}^{b(x)} \\frac{\\partial}{\\partial x} f(x, t) \\, dt")
w("$$")
w()

# ═══════════════════════════════════════════════════════════════════
# SECTION 6: TABLES
# ═══════════════════════════════════════════════════════════════════
w("---")
w()
w("## Section 6: Tables")
w()
w("### Standard Table (5 columns, 10 rows)")
w()
w("| ID | Name | Language | Stars | License |")
w("|-----|------|----------|-------|---------|")
for i in range(1, 11):
    langs = ["Swift", "TypeScript", "Python", "Rust", "Go", "C", "Java", "Kotlin", "Ruby", "Elixir"]
    lics = ["MIT", "Apache-2.0", "GPL-3.0", "BSD-3", "ISC", "MPL-2.0", "MIT", "Apache-2.0", "MIT", "Apache-2.0"]
    w(f"| {i} | Project-{chr(64+i)} | {langs[i-1]} | {i*1234} | {lics[i-1]} |")
w()

w("### Wide Table (12 columns — horizontal scroll test)")
w()
w("| Col1 | Col2 | Col3 | Col4 | Col5 | Col6 | Col7 | Col8 | Col9 | Col10 | Col11 | Col12 |")
w("|------|------|------|------|------|------|------|------|------|-------|-------|-------|")
for i in range(1, 6):
    w(f"| Data-{i}-1 | Data-{i}-2 | Data-{i}-3 | Data-{i}-4 | Data-{i}-5 | Data-{i}-6 | Data-{i}-7 | Data-{i}-8 | Data-{i}-9 | Data-{i}-10 | Data-{i}-11 | Data-{i}-12 |")
w()

w("### Table with Rich Content")
w()
w("| Feature | Status | Notes |")
w("|---------|--------|-------|")
w("| **Bold** editing | `done` | *Italic note* |")
w("| [Link](https://example.com) | ~~removed~~ | `code in cell` |")
w("| $E=mc^2$ | **active** | See [docs](https://example.com) |")
w()

w("### Table with Alignment")
w()
w("| Left | Center | Right |")
w("|:-----|:------:|------:|")
w("| Left aligned text | Centered text | Right aligned text |")
w("| More left | More center | More right |")
w("| Short | Mid | Long content here |")
w()

w("### Minimal Table")
w()
w("| A | B |")
w("|---|---|")
w("| 1 | 2 |")
w()

# ═══════════════════════════════════════════════════════════════════
# SECTION 7: CJK AND INTERNATIONAL TEXT
# ═══════════════════════════════════════════════════════════════════
w("---")
w()
w("## Section 7: CJK and International Text")
w()
w("### Korean (한국어)")
w()
w("Kern 에디터는 한국어 텍스트를 완벽하게 지원합니다. 마크다운 문서를 WYSIWYG 모드로 편집할 수 있으며, 한글 입력기(IME)와 호환됩니다.")
w()
w("프로그래밍에서 가장 중요한 것은 코드의 가독성입니다. 좋은 코드는 다른 개발자가 읽었을 때 쉽게 이해할 수 있어야 하며, 유지보수가 용이해야 합니다. 변수명과 함수명은 그 역할을 명확하게 드러내야 하고, 주석은 '왜'를 설명해야 합니다.")
w()
w("Kern은 macOS 네이티브 앱으로, Swift와 AppKit을 사용하여 개발되었습니다. 웹 에디터 엔진인 Milkdown Crepe를 WKWebView에 로드하여 고품질 마크다운 편집 환경을 제공합니다.")
w()
w("### Japanese (日本語)")
w()
w("日本語のテキストレンダリングテストです。漢字（かんじ）、ひらがな、カタカナの混合テキストが正しく表示されることを確認します。")
w()
w("プログラミングにおいて、コードの品質は非常に重要です。きれいなコードを書くことで、チームの生産性が向上し、バグの発生を抑えることができます。")
w()
w("### Simplified Chinese (简体中文)")
w()
w("这是简体中文文本渲染测试。Kern编辑器应该能够正确显示所有中文字符，包括常用汉字和标点符号。")
w()
w("软件开发是一个持续学习的过程。从需求分析到系统设计，从编码实现到测试部署，每个环节都需要严谨的态度和专业的技能。")
w()
w("### Traditional Chinese (繁體中文)")
w()
w("繁體中文文本測試。確認所有繁體字符能夠正確顯示，包括臺灣和香港地區常用的字體。")
w()
w("### Arabic (العربية) — RTL")
w()
w("هذا نص اختبار باللغة العربية. يجب أن يتم عرض النص من اليمين إلى اليسار بشكل صحيح. البرمجة هي فن وعلم في آن واحد.")
w()
w("### Hebrew (עברית) — RTL")
w()
w("זהו טקסט בדיקה בעברית. הטקסט צריך להיות מוצג מימין לשמאל. תכנות הוא אומנות ומדע כאחד.")
w()
w("### Thai (ภาษาไทย)")
w()
w("ทดสอบการแสดงผลภาษาไทย ตัวอักษรไทยควรแสดงผลได้อย่างถูกต้อง รวมถึงสระ วรรณยุกต์ และตัวเลขไทย ๑๒๓๔๕")
w()
w("### Hindi (हिन्दी)")
w()
w("यह हिंदी पाठ प्रदर्शन परीक्षण है। देवनागरी लिपि में लिखा गया पाठ सही ढंग से प्रदर्शित होना चाहिए।")
w()
w("### Emoji Paragraph")
w()
w("🎉 Welcome to the emoji test! 👋 Here are some common emoji: 🚀 rocket, 💻 laptop, 📝 memo, ✅ check, ❌ cross, ⚠️ warning, 🔥 fire, 💯 100, 🎯 target, 🌈 rainbow, 🦀 crab (Rust!), 🐍 snake (Python!), ☕ coffee (Java!), 💎 gem (Ruby!), 🍎 apple (Swift!)")
w()
w("### Mixed Scripts")
w()
w("This paragraph mixes English with 한국어 Korean, 日本語 Japanese, 中文 Chinese, العربية Arabic, and emoji 🌏. All should render correctly in the same line without layout breaking.")
w()

with open(OUT, 'a') as f:
    f.write('\n'.join(lines))

print(f"Part 2 appended: {len(lines)} lines")
