#!/usr/bin/env python3
"""Sync a deterministic permutation appendix into mega-stress-test.md.

The appendix embeds the full ultimate fixture plus an action-program matrix,
so the mega fixture is both volume-dense and permutation-dense in one file.
"""

from __future__ import annotations

from itertools import product
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MEGA = ROOT / "test-fixtures" / "mega-stress-test.md"
ULTIMATE = ROOT / "test-fixtures" / "ultimate-stress-test.md"

BEGIN = "<!-- BEGIN PERMUTATION APPENDIX -->"
END = "<!-- END PERMUTATION APPENDIX -->"


def action_program_lines(max_depth: int = 3) -> list[str]:
    actions = [
        "moveLeft",
        "moveRight",
        "moveLineStart",
        "moveLineEnd",
        "moveDocumentStart",
        "moveDocumentEnd",
        "insertASCII_then_backspace",
        "insertNewline_then_backspace",
        "space_then_backspace",
        "selectWord_preserve",
        "selectLine_preserve",
        "cut_then_paste",
        "undo_then_redo",
        "toggleBold_twice",
        "toggleItalic_twice",
        "toggleCode_twice",
    ]

    lines: list[str] = []
    for depth in range(1, max_depth + 1):
        lines.append(f"#### Depth {depth}")
        lines.append("")
        for seq in product(actions, repeat=depth):
            lines.append(f"- {' + '.join(seq)}")
        lines.append("")
    return lines


def build_appendix(ultimate_text: str) -> str:
    lines: list[str] = []
    lines.append(BEGIN)
    lines.append("")
    lines.append("## Section 12: Permutation Core (Embedded Ultimate Fixture)")
    lines.append("")
    lines.append("This section is auto-generated by scripts/sync_mega_permutation_appendix.py.")
    lines.append("It guarantees that mega-stress-test.md contains all feature combinations and action seeds.")
    lines.append("")
    lines.append("### UI Action Program Matrix")
    lines.append("")
    lines.append("Generated action programs used by exhaustive typing/action tests:")
    lines.append("")
    lines.extend(action_program_lines(max_depth=3))
    lines.append("### Embedded Ultimate Fixture")
    lines.append("")
    lines.extend(ultimate_text.rstrip("\n").splitlines())
    lines.append("")
    lines.append(END)
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not MEGA.exists():
        raise SystemExit(f"Missing mega fixture: {MEGA}")
    if not ULTIMATE.exists():
        raise SystemExit(f"Missing ultimate fixture: {ULTIMATE}")

    mega = MEGA.read_text(encoding="utf-8")
    ultimate = ULTIMATE.read_text(encoding="utf-8")
    appendix = build_appendix(ultimate)

    if BEGIN in mega and END in mega:
        prefix = mega.split(BEGIN, 1)[0].rstrip("\n")
    else:
        prefix = mega.rstrip("\n")

    merged = f"{prefix}\n\n{appendix}"
    MEGA.write_text(merged, encoding="utf-8")
    print(f"Updated {MEGA}")


if __name__ == "__main__":
    main()
